# Generated by Django 3.2.6 on 2022-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveladmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldb',
            name='dname',
        ),
        migrations.AddField(
            model_name='traveldb',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
